version: "3.9"

services:
  postgres:
    container_name: water-groove-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: water_groove
      POSTGRES_USER: watergroove_user
      POSTGRES_PASSWORD: watergoover256
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U watergroove_user -d water_groove"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
